Revert "handling of luaposix for dynamic environments"
This reverts commit 9edb7c4e039e3dcb7914f4eb9d8a374d19e32dd1.

sorry, it breaks the build (the trivial #endif -> #else and
additional "error: 'report' was not declared in this scope)"


Origin commit data
------------------
Commit: https://github.com/TangoCash/neutrino-tangos/commit/8c88dfdc204577cbbc4ecb7af07882c0ff373245
Author: Stefan Seyfried <seife@tuxbox-git.slipkontur.de>
Date: 2013-04-27 (Sat, 27 Apr 2013)



------------------
This commit was generated by Migit