Revert "- movieplayer: allow screenshots from stream"
- sh4 build not ok

"/build_source/neutrino-mp-ddt/src/gui/movieplayer.cpp:3524:9: error: 'put_time' is not a member of 'std'
ss << std::put_time(&tm, "%Y%m%d_%H%M%S");"

This reverts commit 345a8852f9b7af62693ef3478c692e7303a4aa2f.


Origin commit data
------------------
Commit: https://github.com/TangoCash/neutrino-tangos/commit/621b85c963ef28beb27c3660722879a57ea5afb2
Author: Frankenstone <dampf_acc@online.de>
Date: 2019-03-18 (Mon, 18 Mar 2019)



------------------
This commit was generated by Migit